name: Push latest
on:
  push:
    branches:
      - develop
jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
    - name: Copia repositorio
      uses: actions/checkout@main
    - name: Construye imagen
      run: docker build --tag islasgeci/population_trend:latest --tag islasgeci/population_trend:${GITHUB_SHA:0:4} .
    - name: Verifica el formato
      run: docker run islasgeci/population_trend:latest make check
    - name: Corre pruebas y evalúa cobertura
      run: docker run --volume $PWD:/workdir islasgeci/population_trend:latest make coverage
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml
        verbose: true
    - name: Create/Update tag
      uses: rickstaa/action-create-tag@v1.5.4
      with:
        tag: "latest"
        message: "Latest release"
        force_push_tag: true
    - name: Docker log-in
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
    - name: Sube latest a Docker Hub
      run: docker push islasgeci/population_trend:latest
    - name: Sube sha a Docker Hub
      run: docker push islasgeci/population_trend:${GITHUB_SHA:0:4}
    - name: Set up Python 3.9
      uses: actions/setup-python@master
      with:
        python-version: 3.9
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_TOKEN }}
        skip_existing: true
  mutants:
      runs-on: ubuntu-latest
      steps:
      - name: Copia repositorio
        uses: actions/checkout@v3
      - name: Construye imagen
        run: docker build --tag islasgeci/population_trend:latest .
      - name: Evalúa resistencia a mutaciones
        run: docker run -v $PWD:/workdir islasgeci/population_trend:latest make mutants
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: mutant-registry
          path: html/
